name: gmailctl
version: git
confinement: strict
summary: Tool to generate and maintain Gmail filters in a declarative way
description: Tool to generate and maintain Gmail filters in a declarative way

grade: stable
base: core20

parts:
  gmailctl:
    plugin: go
    source-type: git
    source: https://github.com/gjolly/gmailctl.git
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git describe --tags --abbrev=0)"
      git checkout "${last_committed_tag}"
      snapcraftctl set-version "$(git describe --tags)"

apps:
  gmailctl:
    command: bin/gmailctl
